// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaceMS.Entities.NguyenDNT.Models;

public partial class JockeyNguyenDnt
{
    public int JockeyNguyenDntid { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string LicenseCode { get; set; }

    public decimal? Weight { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<RegistrationNguyenDnt> RegistrationNguyenDnts { get; set; } = new List<RegistrationNguyenDnt>();
}