// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaceMS.Entities.NguyenDNT.Models;

public partial class RegistrationNguyenDnt
{
    public int RegistrationNguyenDntid { get; set; }

    public string RaceName { get; set; }

    public string HorseName { get; set; }

    public DateTime? RegisteredDate { get; set; }

    public DateTime? ResponseDate { get; set; }

    public decimal? PrizeMoney { get; set; }

    public bool? IsConfirmed { get; set; }

    public string Note { get; set; }

    public int? JockeyNguyenDntid { get; set; }

    public virtual JockeyNguyenDnt JockeyNguyenDnt { get; set; }
}