// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using RaceMS.Entities.NguyenDNT.Models;
using System;
using System.Collections.Generic;

//namespace RaceMS.Repositories.NguyenDNT.Models;
namespace RaceMS_Repositories.NguyenDNT.DBContext;

public partial class RaceManagementDBContext : DbContext
{
    public RaceManagementDBContext()
    {
    }

    public RaceManagementDBContext(DbContextOptions<RaceManagementDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<JockeyNguyenDnt> JockeyNguyenDnts { get; set; }

    public virtual DbSet<RegistrationNguyenDnt> RegistrationNguyenDnts { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("Data")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=ASUS-1412\\SQLEXPRESS;Initial Catalog=RaceManagementDB;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Vietnamese_CI_AS");

        modelBuilder.Entity<JockeyNguyenDnt>(entity =>
        {
            entity.HasKey(e => e.JockeyNguyenDntid).HasName("PK__JockeyNg__3125A38184277CF9");

            entity.ToTable("JockeyNguyenDNT");

            entity.Property(e => e.JockeyNguyenDntid).HasColumnName("JockeyNguyenDNTId");
            entity.Property(e => e.DateOfBirth).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LicenseCode).HasMaxLength(50);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<RegistrationNguyenDnt>(entity =>
        {
            entity.HasKey(e => e.RegistrationNguyenDntid).HasName("PK__Registra__34CA14853DF0E789");

            entity.ToTable("RegistrationNguyenDNT");

            entity.Property(e => e.RegistrationNguyenDntid).HasColumnName("RegistrationNguyenDNTId");
            entity.Property(e => e.HorseName).HasMaxLength(150);
            entity.Property(e => e.JockeyNguyenDntid).HasColumnName("JockeyNguyenDNTId");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.PrizeMoney).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RaceName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RegisteredDate).HasColumnType("datetime");
            entity.Property(e => e.ResponseDate).HasColumnType("datetime");

            entity.HasOne(d => d.JockeyNguyenDnt).WithMany(p => p.RegistrationNguyenDnts)
                .HasForeignKey(d => d.JockeyNguyenDntid)
                .HasConstraintName("FK__Registrat__Jocke__398D8EEE");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}